// Dashboard names backed by the shared English catalogue.
import { translate } from '../i18n'

export const dashboardCopy = {
  status: translate('dashboard.overview.status'),
  statusSub: translate('dashboard.overview.statusSub'),
  conclusion: translate('dashboard.overview.conclusion'),
  coverage: translate('dashboard.overview.coverage'),
  coverageComplete: translate('dashboard.overview.coverageComplete'),
  coverageRunning: translate('dashboard.overview.coverageRunning'),
  coveragePending: translate('dashboard.overview.coveragePending'),
  coverageEmpty: translate('dashboard.overview.coverageEmpty'),
  coverageFailed: translate('dashboard.overview.coverageFailed'),
  coverageCompleteSub: translate('dashboard.overview.coverageCompleteSub'),
  coveragePendingSub: translate('dashboard.overview.coveragePendingSub'),
  coverageRunningSub: translate('dashboard.overview.coverageRunningSub'),
  coverageFailedSub: translate('dashboard.overview.coverageFailedSub'),
  coverageEmptySub: translate('dashboard.overview.coverageEmptySub'),
  assessmentEmpty: translate('dashboard.overview.assessmentEmpty'),
  assessmentEmptySub: translate('dashboard.overview.assessmentEmptySub'),
  assessmentConfirmedSub: translate('dashboard.overview.assessmentConfirmedSub'),
  assessmentInProgressSub: translate('dashboard.overview.assessmentInProgressSub'),
  assessmentPendingSub: translate('dashboard.overview.assessmentPendingSub'),
  assessmentReviewedSub: translate('dashboard.overview.assessmentReviewedSub'),
  assessmentNoFindingsSub: translate('dashboard.overview.assessmentNoFindingsSub'),
  next: translate('dashboard.overview.next'),
  nextSub: translate('dashboard.overview.nextSub'),
  also: translate('dashboard.overview.also'),
  outstanding: translate('dashboard.overview.outstanding'),
  outstandingCount: translate('dashboard.overview.outstandingCount'),
  outstandingOne: translate('dashboard.overview.outstandingOne'),
  confirmed: translate('dashboard.overview.confirmed'),
  confirmedCount: translate('dashboard.overview.confirmedCount'),
  confirmedOne: translate('dashboard.overview.confirmedOne'),
  reviewed: translate('dashboard.overview.reviewed'),
  reviewedSub: translate('dashboard.overview.reviewedSub'),
  review: translate('dashboard.overview.review'),
  reviewCount: translate('dashboard.overview.reviewCount'),
  reviewOne: translate('dashboard.overview.reviewOne'),
  openConfirmed: translate('dashboard.overview.openConfirmed'),
  openDismissed: translate('dashboard.overview.openDismissed'),
  noResults: translate('dashboard.overview.noResults'),
  noResultsSub: translate('dashboard.overview.noResultsSub'),
  unresolved: translate('dashboard.overview.unresolved'),
  accepted: translate('dashboard.overview.accepted'),
  evidence: translate('dashboard.overview.evidence'),
  evidenceSub: translate('dashboard.overview.evidenceSub'),
  sources: translate('dashboard.overview.sources'),
  software: translate('dashboard.overview.software'),
  softwareSub: translate('dashboard.overview.softwareSub'),
  softwarePending: translate('dashboard.overview.softwarePending'),
  softwareUnknown: translate('dashboard.overview.softwareUnknown'),
  softwareLogsOnly: translate('dashboard.overview.softwareLogsOnly'),
  softwareOpen: translate('dashboard.overview.softwareOpen'),
  versionUnknown: translate('dashboard.overview.versionUnknown'),
  correctedVersion: translate('dashboard.overview.correctedVersion'),
  database: translate('dashboard.overview.database'),
  databaseOpen: translate('dashboard.overview.databaseOpen'),
  databaseVersionSource: translate('dashboard.overview.databaseVersionSource'),
  available: translate('dashboard.overview.available'),
  sourceCount: translate('dashboard.overview.sourceCount'),
  sourceOne: translate('dashboard.overview.sourceOne'),
  fileCount: translate('dashboard.overview.fileCount'),
  fileOne: translate('dashboard.overview.fileOne'),
  availableEmpty: translate('dashboard.overview.availableEmpty'),
  evidenceOpen: translate('dashboard.overview.evidenceOpen'),
  requests: translate('dashboard.overview.requests'),
  clients: translate('dashboard.overview.clients'),
  logPeriod: translate('dashboard.overview.logPeriod'),
  top: translate('dashboard.top.title'),
  topSub: translate('dashboard.top.sub'),
  topOpen: translate('dashboard.top.open'),
  topExample: translate('dashboard.top.example'),
  topPending: translate('dashboard.top.pending'),
  topPendingSub: translate('dashboard.top.pendingSub'),
  topUnavailable: translate('dashboard.top.unavailable'),
  topUnavailableSub: translate('dashboard.top.unavailableSub'),
  topOther: translate('dashboard.top.other'),
  topOtherSub: translate('dashboard.top.otherSub'),
  topDismissed: translate('dashboard.top.dismissed'),
  topDismissedSub: translate('dashboard.top.dismissedSub'),
  topNone: translate('dashboard.top.none'),
  topNoneSub: translate('dashboard.top.noneSub'),
  topCategories: {
    webshell: translate('dashboard.top.category.webshell'),
    obfuscation: translate('dashboard.top.category.obfuscation'),
    htaccess: translate('dashboard.top.category.htaccess'),
    yara: translate('dashboard.top.category.yara'),
    db_injected: translate('dashboard.top.category.db_injected'),
    shell_access: translate('dashboard.top.category.shell_access'),
    bruteforce: translate('dashboard.top.category.bruteforce'),
    probes: translate('dashboard.top.category.probes'),
    scanner: translate('dashboard.top.category.scanner'),
  },
  extensions: {
    plugin: [translate('dashboard.overview.extensions.plugin.one'), translate('dashboard.overview.extensions.plugin.many')],
    'mu-plugin': [translate('dashboard.overview.extensions.mu-plugin.one'), translate('dashboard.overview.extensions.mu-plugin.many')],
    theme: [translate('dashboard.overview.extensions.theme.one'), translate('dashboard.overview.extensions.theme.many')],
    component: [translate('dashboard.overview.extensions.component.one'), translate('dashboard.overview.extensions.component.many')],
    module: [translate('dashboard.overview.extensions.module.one'), translate('dashboard.overview.extensions.module.many')],
    template: [translate('dashboard.overview.extensions.template.one'), translate('dashboard.overview.extensions.template.many')],
    language: [translate('dashboard.overview.extensions.language.one'), translate('dashboard.overview.extensions.language.many')],
  },
  loading: translate('dashboard.overview.loading'),
  error: translate('dashboard.overview.error'),
  errorSub: translate('dashboard.overview.errorSub'),
  retry: translate('dashboard.overview.retry'),
  actions: {
    evidence: [translate('dashboard.overview.actions.evidence.title'), translate('dashboard.overview.actions.evidence.hint')],
    analysis: [translate('dashboard.overview.actions.analysis.title'), translate('dashboard.overview.actions.analysis.hint')],
    running: [translate('dashboard.overview.actions.running.title'), translate('dashboard.overview.actions.running.hint')],
    issue: [translate('dashboard.overview.actions.issue.title'), translate('dashboard.overview.actions.issue.hint')],
    pending: [translate('dashboard.overview.actions.pending.title'), translate('dashboard.overview.actions.pending.hint')],
    triage: [translate('dashboard.overview.actions.triage.title'), translate('dashboard.overview.actions.triage.hint')],
    warnings: [translate('dashboard.overview.actions.warnings.title'), translate('dashboard.overview.actions.warnings.hint')],
    hunt: [translate('dashboard.overview.actions.hunt.title'), translate('dashboard.overview.actions.hunt.hint')],
    report: [translate('dashboard.overview.actions.report.title'), translate('dashboard.overview.actions.report.hint')],
  },
} as const
